import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";

const sourcePaths = {
  home: new URL("../src/app/page.tsx", import.meta.url),
  layout: new URL("../src/app/layout.tsx", import.meta.url),
  navigation: new URL("../src/components/AppNav.tsx", import.meta.url),
  workspace: new URL(
    "../src/app/cases/[id]/CaseWorkspaceClient.tsx",
    import.meta.url
  ),
  stickyHeader: new URL(
    "../src/app/cases/[id]/components/StickyOperationalHeader.tsx",
    import.meta.url
  ),
  patientEntry: new URL("../src/app/cases/PatientEntryCard.tsx", import.meta.url),
  newPatient: new URL("../src/app/new-case/page.tsx", import.meta.url),
};

async function readSource(path) {
  return readFile(path, "utf8");
}

function renderedText(source) {
  return source.replaceAll("&apos;", "'").replace(/\s+/g, " ");
}

test("home presents the continuity platform identity and patient-first actions", async () => {
  const home = renderedText(await readSource(sourcePaths.home));

  assert.match(home, /Clinical Continuity Platform/);
  assert.match(
    home,
    /Preserves clinical meaning across time so clinicians don't have to repeatedly reconstruct it\./
  );
  assert.match(home, /> View Patients </);
  assert.match(home, /> Add Patient </);
  assert.doesNotMatch(home, /Select Discipline/);
  assert.doesNotMatch(home, /View Saved Cases/);
});

test("app metadata uses the continuity platform title and description", async () => {
  const layout = renderedText(await readSource(sourcePaths.layout));

  assert.match(layout, /title: "Clinical Continuity Platform"/);
  assert.match(
    layout,
    /Preserves clinical meaning across time so clinicians don't have to repeatedly reconstruct it\./
  );
  assert.doesNotMatch(layout, /Create Next App|Generated by create next app/);
});

test("global navigation uses patient-centered platform labels", async () => {
  const navigation = renderedText(await readSource(sourcePaths.navigation));

  assert.match(navigation, /Clinical Continuity Platform/);
  assert.match(navigation, /> Add Patient </);
  assert.match(navigation, /> Patients </);
  assert.doesNotMatch(navigation, /OT Clinical Reasoning Assistant|> New Case <|> Cases </);
});

test("patient workspace preserves approved labels while normalizing patient context", async () => {
  const [workspace, stickyHeader, patientEntry, newPatient] = await Promise.all([
    readSource(sourcePaths.workspace),
    readSource(sourcePaths.stickyHeader),
    readSource(sourcePaths.patientEntry),
    readSource(sourcePaths.newPatient),
  ]);
  const combined = renderedText(
    [workspace, stickyHeader, patientEntry, newPatient].join("\n")
  );

  assert.match(combined, /Visit Briefing/);
  assert.match(combined, /Case Details/);
  assert.match(combined, /Unnamed Patient Record/);
  assert.match(combined, /Return to Current Patient/);
  assert.doesNotMatch(combined, /Return to Live Case|Untitled Case|New (?:OT|PT) Case/);
  assert.doesNotMatch(combined, /Patient History/);
});
